spring:
  application:
    name: app
  datasource:
    url: jdbc:postgresql://localhost:5432/citronix
    username: postgres
    password: 123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true